server:
    tomcat:
        threads:
            max: 10

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        username: test
        password: test
        hikari:
            connectionTimeout: 30000
            maximumPoolSize: 10
            minimumIdle: 10
